v1.0 - change the rule for optional inputs
-ref option cancelled. Optional inputs are read from the main input .in file. The keywords specifying inputs in .in file should be specified in 'settings'

diff --git a/LAMMPS_job_sub_ICHPC/runPlmp b/LAMMPS_job_sub_ICHPC/runPlmp
--- a/LAMMPS_job_sub_ICHPC/runPlmp
+++ b/LAMMPS_job_sub_ICHPC/runPlmp
@@ -4,9 +4,9 @@
 
 function get_input_ {
 
-    ## Useful variables: JOBNAME, REFNAME, LMP_OPT: other options of lammps
+    ## Useful variables: JOBNAME, LMP_OPT: other options of lammps
 
-    param_list=$(getopt -a -l in:,ref: -n "$0" -- ${in_var} 2> /dev/null) 
+    param_list=$(getopt -a -l in: -n "$0" -- ${in_var} 2> /dev/null) 
     echo ${param_list}
 
     eval set -- "${param_list}"
@@ -15,8 +15,6 @@ function get_input_ {
         case $1 in
         --in ) 
             shift; JOBNAME=$1 ;;
-        --ref )  
-            shift; REFNAME=$1 ;;
         -- ) 
             shift;
             while [[ ! -z $1 ]]; do
@@ -148,40 +146,7 @@ fi
 
 echo "temporary directory: ${JOBTMPDIR}"
 
-# Prepare input files
-
-## Restart file: refname.restart.stepnumber, edit the main input file
-
-if [[ ! -z ${REFNAME} ]]; then
-
-    if [[ ${REFNAME%%.*} == ${JOBNAME} ]]; then
-        echo "Warning: Restart file has the same name as current job."
-    fi
-
-    if [[ ${REFNAME} == '*.restart*' ]]; then
-        echo "Error: Incorrect restart file name, '.restart*' pattern not found."
-        exit
-    fi
-
-    TMP_NAME=${REFNAME}
-
-### Find the restart file
-
-    cp ${INPDIR}/${REFNAME} ${JOBTMPDIR}/${TMP_NAME}
-    echo "Restart file found: ${INPDIR}/${REFNAME}, temporarily saved as ${JOBTMPDIR}/${TMP_NAME}" >> ${OUTDIR}/${OUTPUT} 2>&1
-    echo "Restart file found: ${INPDIR}/${REFNAME}, temporarily saved as ${JOBTMPDIR}/${TMP_NAME}" 
-
-    if [[ ! -z ${PCLIST} ]]; then
-        for PC in ${PCLIST[@]}; do
-            ssh ${PC} "cp ${INPDIR}/${REFNAME} ${JOBTMPDIR}/${TMP_NAME}"
-            echo "File synchonised on ${PC} : ${JOBTMPDIR}/${TMP_NAME}"
-        done
-    fi
-
-    sed -i '/read_restart/d' ${JOBNAME}.in 2> /dev/null
-    sed -i '1i\# auto_generated read_restart line ' ${JOBNAME}.in
-    sed -i "1a\read_restart    ${TMP_NAME}" ${JOBNAME}.in
-fi
+# Prepare input file
 
 ## Read list
 
@@ -191,9 +156,9 @@ LINE_PRECALC=`echo "scale=0;${LINE_PRECALC%%:*}+4" | bc`
 SAVED_NAME=`awk 'NR=="'${LINE_PRECALC}'"{printf("%s", $1)}' ${SETFILE}`
 TMP_NAME=`awk 'NR=="'${LINE_PRECALC}'"{printf("%s", $2)}' ${SETFILE}`
 
-## Mandatory & optional files
+## Mandatory files: jobname.in etc
 
-while [[ ${TMP_NAME} != 'RESTART' ]]; do
+while [[ ${SAVED_NAME} != *'------------'* ]]; do
     SAVED_NAME="${JOBNAME}.${SAVED_NAME#*.}"
     TMP_NAME="${JOBNAME}.${TMP_NAME#*.}"
 
@@ -215,12 +180,55 @@ while [[ ${TMP_NAME} != 'RESTART' ]]; do
             done
         fi
     else
-        echo "Input data ${INPDIR}/${SAVED_NAME} not found or empty."
+        echo "ERROR: Mandatory input ${INPDIR}/${SAVED_NAME} not found or empty."
+        exit
     fi
 
     LINE_PRECALC=`echo "scale=0;${LINE_PRECALC}+1" | bc`
     SAVED_NAME=`awk 'NR=="'${LINE_PRECALC}'"{printf("%s", $1)}' ${SETFILE}`
     TMP_NAME=`awk 'NR=="'${LINE_PRECALC}'"{printf("%s", $2)}' ${SETFILE}`
+done
+
+## External files
+
+LINE_EXT=`grep -nw 'FILE_EXT' ${SETFILE}`
+LINE_EXT=`echo "scale=0;${LINE_EXT%%:*}+4" | bc`
+
+COMMAND=`awk 'NR=="'${LINE_EXT}'"{printf("%s", $1)}' ${SETFILE}`
+
+while [[ ${COMMAND} != *'------------'* ]]; do
+    grep "${COMMAND}" ${INPDIR}/${JOBNAME}.in > /dev/null 2>&1 
+
+    if [[ $? == 0 ]]; then
+        lines=`sed -n "/${COMMAND}/=" ${INPDIR}/${JOBNAME}.in`
+        lines=(${lines// /})
+        for line in ${lines[@]}; do
+            EXT_NAME=`awk 'NR=='"${line}"'{printf "%s", $2}' ${INPDIR}/${JOBNAME}.in | sed 's/\"//g'`
+            if [[ -e ${INPDIR}/${EXT_NAME} && -s ${INPDIR}/${EXT_NAME} ]]; then
+
+### Copy files to the main temporary directory
+
+                echo "input expected in ${INPDIR}/${EXT_NAME}"
+                echo "input data ${INPDIR}/${EXT_NAME}" >> ${OUTDIR}/${OUTPUT} 2>&1
+                cp ${INPDIR}/${EXT_NAME} ${JOBTMPDIR}/${EXT_NAME}
+                echo "input ${EXT_NAME} copied."
+
+### Synchonise files on all nodes
+
+                if [[ ! -z ${PCLIST} ]]; then
+                    for PC in ${PCLIST[@]}; do
+                        ssh ${PC} "cp ${INPDIR}/${EXT_NAME} ${JOBTMPDIR}/${EXT_NAME}"
+                        echo "File synchonised on ${PC} : ${JOBTMPDIR}/${EXT_NAME}"
+                    done
+                fi
+            else
+                echo "Input data ${INPDIR}/${EXT_NAME} not found or empty."
+            fi
+        done
+    fi
+
+    LINE_EXT=`echo "scale=0;${LINE_EXT}+1" | bc`
+    COMMAND=`awk 'NR=="'${LINE_EXT}'"{printf("%s", $1)}' ${SETFILE}`
 done
 
 echo "All files are synchonised." >> ${OUTDIR}/${OUTPUT}
